# Generated by Django 2.1.1 on 2018-09-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('symbol', models.CharField(max_length=5, verbose_name='símbolo')),
            ],
            options={
                'verbose_name': 'moeda',
                'verbose_name_plural': 'moedas',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='valor')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.Currency', verbose_name='moeda')),
            ],
            options={
                'verbose_name': 'taxa de câmbio',
                'verbose_name_plural': 'taxas de câmbio',
            },
        ),
    ]
