# Generated by Django 2.1.1 on 2018-09-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='central_bank_reference',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
