# Generated by Django 2.1.1 on 2018-09-24 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_central_bank_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
